[package]
name = 'bash-object'
slug = 'bash_object'
version = '0.1.0'
authors = ['Edwin Kofler" <edwin@kofler.dev>']
description = 'A kickass Toml parser written in pure Bash'

[run]
dependencies = ['hyperupcall/bash-object@v0.6.3', 'https://github.com/hyperupcall/bats-common-utils.git@v3.0.0']
sourceDirs = ['pkg/lib/commands', 'pkg/lib/public', 'pkg/lib/util']
builtinDirs = []
binDirs = []
completionDirs = []
manDirs = []

[run.shellEnvironment]

[run.setOptions]

[run.shoptOptions]
